import torch
import torch.nn as nn
import functools

class HRankChannelScorer:
    """
    HRank: Filter Pruning using High-Rank Feature Map.
    
    Reference:
    Lin et al., "HRank: Filter Pruning using High-Rank Feature Map", CVPR 2020.
    
    Idea:
    - Feature maps with High Rank contain more information.
    - Feature maps with Low Rank are redundant.
    - Rank is calculated on the feature map generated by a batch of images.
    - Score = Average Rank over the batch.
    """
    def __init__(self, model):
        self.model = model
        self.activations = {}
        self.hooks = []
        self._register_hooks()

    def _register_hooks(self):
        def get_activation(name):
            def hook(model, input, output):
                # output shape: (Batch, Channels, H, W)
                # Store a reference or clone? 
                # Cloning consumes memory. We usually compute rank on the fly if possible,
                # but the scorer interface separates "collect" from "score".
                # Let's store a small batch or average rank directly to save memory.
                
                # Compute rank immediately to save memory
                with torch.no_grad():
                    # output: (B, C, H, W)
                    if output.dim() == 4:
                        B, C, H, W = output.shape
                        # Flatten H,W: (B, C, H*W) -> Actually HRank does SVD on (H, W) matrix?
                        # Paper: "The rank of feature maps... generated by input image... feature map is a matrix."
                        # Yes, for each channel c, feature map is HxW.
                        # Rank(F_c) is rank of this HxW matrix.
                        
                        # Reshape to (B*C, H, W)
                        x = output.view(-1, H, W) 
                        
                        # Compute matrix rank
                        # torch.linalg.matrix_rank is slow on GPU sometimes, or SVD.
                        # SVD is robust.
                        try:
                            # Use SVD to estimate rank (number of singular values > threshold)
                            # Or just torch.linalg.matrix_rank(x)
                            # Default tol is fine.
                            ranks = torch.linalg.matrix_rank(x) # (B*C,)
                        except:
                            # Fallback if matrix_rank fails
                            # Use simplistic SVD
                            _, S, _ = torch.linalg.svd(x, full_matrices=False)
                            # Count non-zero singular values (with tolerance)
                            tol = S.max(dim=-1, keepdim=True)[0] * max(H, W) * 1e-7
                            ranks = (S > tol).sum(dim=-1)

                        ranks = ranks.view(B, C).float().mean(dim=0) # Average over batch -> (C,)
                        
                        if name not in self.activations:
                            self.activations[name] = []
                        self.activations[name].append(ranks)
                        
            return hook

        for name, module in self.model.named_modules():
            if isinstance(module, nn.Conv2d):
                self.hooks.append(module.register_forward_hook(get_activation(name)))

    def collect_ranks(self, data_loader, device, num_batches=5):
        """
        Run forward pass to collect ranks.
        """
        self.model.eval()
        self.activations = {} # Reset
        
        with torch.no_grad():
            for i, (inputs, _) in enumerate(data_loader):
                if i >= num_batches:
                    break
                inputs = inputs.to(device)
                _ = self.model(inputs)
                
    def get_score(self, layer_name, layer_module, **kwargs):
        """
        Return pre-computed HRank score.
        """
        if layer_name not in self.activations:
            # If no activations recorded (e.g. mock run), return random or L1 fallback
            # print(f"Warning: No activations for {layer_name}, falling back to L1")
            # Fallback to L1 logic just to not crash
            return layer_module.weight.data.abs().view(layer_module.weight.size(0), -1).sum(dim=1)
        
        # Average over collected batches
        # self.activations[layer_name] is a list of tensors (C,)
        ranks_list = self.activations[layer_name]
        avg_ranks = torch.stack(ranks_list).mean(dim=0) # (C,)
        
        return avg_ranks

    def remove_hooks(self):
        for h in self.hooks:
            h.remove()
